### ISSUE TITLE
Example picture for the readme...

### ISSUE THREAD

**Issue by barry-bookinglive** [flashbackzoo/silverstripe-charts#3]
Hi David,

I made this picture to see what the charts would look like, I thought I'd send it to you for inclusion in the readme so others can see too what the output is.

![examplebarchart](https://cloud.githubusercontent.com/assets/8995766/10868309/bbb3117c-8082-11e5-8043-544dba5b3b34.jpg)

**Comment by flashbackzoo** [comment]
Awesome - thanks Barry. I'll include it in the readme. I've been meaning to do some more work on this module, this might be a good chance :smile:

**Comment by flashbackzoo** [comment]
@barry-bookinglive finally added your screenshot. Thanks for that - I'm going to work on the module this weekend.
